### ISSUE TITLE
Before filing a socket not closed issue: understanding async I/O + ordering + OS differences + stability requirements

### ISSUE THREAD

**Issue by eriktrom** [http-party/node-portfinder#99]
write contributor guidelines, including emphasis on development of port finding:

- [ ] stability over speed, 
- [ ] stability over features that don't serve the larger portion of the consumer base (aka, wrap this lib if you want to extend it, provide examples and how to's for those in need).
- [ ] edge cases (per OS, mentioned many times in discussion, but mainly 1) macOS touch bar takes ports 40,000-60,000, so exclude those) 2) Windows (in the past) has allowed port rebinding
- [ ] How to wrap portfinder for your own custom need  (in order to leave this lib encapsulated to one task that is done well (unix/substack philosophy).

---- 
>
Summary: (from https://github.com/http-party/node-portfinder/pull/105#issuecomment-642807837)
>
> Here is what I would consider:
>
> not modifying this library, except under one circumstance
that another library, call it portlocker™️, that wraps port finder to find a port, but then also maintains that open socket, which can then be used via a callback
--
Reasoning:
>
> We have no idea how this lib is being consumed - with 7+ million npm downloads a week, we don't want to break anything nor anyones expectations of its current behavior
>
> Such a library, like portlocker™️, can then do one thing and do it well - handle the happens before ordering of async i/o scheduling. This would allow risk free iteration on current and future needs, anything from single threaded async i/o to multi (worker or process) async i/o could be explored. There has been some interest in this by others, in various forms, none of which are core to portfinder's original goals or intents, but which could easily consume portfinder and add such things.
>
> If this proposal gains traction, I will consider. Provide a 👍, and I'll tally the priority and interest.>
>
> Keeps the comments light, but feel free to weigh in

**Comment by eriktrom** [comment]
Consolidate with:

- [ ] all cross refs found at #105 that are 
- [ ] move ad hoc summary and proposal found randomly in comment @ #105: https://github.com/http-party/node-portfinder/pull/105#issuecomment-642807837

**Comment by eriktrom** [comment]
too much scope, closing for now
